using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/*
 * events generated by the script:
 *		void onResourceSpend(float amount);
 *		void onResourceLack(float amount);
 */
public class ResourceController : MonoBehaviour {

	public string type;
	public float actual = 100.0f;
	public float max = 100.0f;
	// health regeneration in units/s 
	public float regeneration = 0.0f;

	protected void Update()
	{
		Gain(regeneration * Time.deltaTime);
	}

	void OnResourceSpend(float required){}
	void OnResourceLack(float required){}

	public bool HasEnough(float required)
	{
		return required < actual;
	}
	public bool Spend(float required)
	{
		if (HasEnough(required))
		{
			actual -= required;
			BroadcastMessage("OnResourceSpend", required);
			return true;
		}
		BroadcastMessage("OnResourceLack", required);
		return false;
	}
	public void Gain(float amount)
	{
		actual = Mathf.Clamp(actual + amount, 0, max);
	}


}
